### ISSUE TITLE
recipe?  repair?

### ISSUE THREAD

**Issue by gregglind** [mozilla/self-repair-server#1]

**Comment by MattGrimes** [comment]
Is this a question about naming? My preference would be recipe (or something else) instead of repair. I think we'll be doing a lot of things with this tool beyond just fixing issues. Heartbeat is a good example of that. It isn't a "repair" of any sort. There will be others that fall into the educate, promote, and delight users categories.

**Comment by gregglind** [comment]
11:15 < gregglind> recipes?  Fixes?  surgeries?  jails?  plus+1?  awesomeup? unfsck?
11:15 < gregglind> what are these self-heal things?
11:17 <~Tyler> gregglind: I say we stick with recipes and make them part of Firefox cookbook, which we publish and sell once a year as part of the annual fundraising.
               It will provide until now untold solutions on how to fix mysterious Firefox problems and can be sold on checkout racks around the world
11:17 < gregglind> you are silly.
11:18 < gregglind> so these things can sit around and wait for bad things, btw.  They don't have to be 'instant'
11:18 < gregglind> which means they can power any contextual trigger.

**Comment by gregglind** [comment]
So, yes, this is the naming question.  

In the code, I can call them "filters" and "actions", but that is not terribly exciting

**Comment by MattGrimes** [comment]
I do like recipes and I think we are already using it for the most part. However, we are going to be meeting with Brand/Creative soon to talk about this. We might want to stick with the "medical" theme that we've been using elsewhere. Maybe something like prescriptions?

**Comment by gregglind** [comment]
These are called recipes.
