### ISSUE TITLE
PBM Genpop HB survey for Germany

### ISSUE THREAD

**Issue by gregglind** [mozilla/self-repair-server#174]
Release genpop pbm survey in german (http://qsurvey.mozilla.com/s3/PBM-Survey-Genpop-41-German) to release population, as the POST HEARTBEAT survey.

Release to 100% of germany (HB respondents) ON RELEASE ONLY.

NO USA.

PB-MODE-SURVEY: SHOULD BE OFF FOR ALL COUNTRIES.

**Comment by rjweiss** [comment]
Genpop private browsing survey for de SHOULD BE ON (https://qsurvey.mozilla.com/s3/PBM-Survey-Genpop-41-German)
Genpop private browsing survey for en-us SHOULD BE ON (https://qsurvey.mozilla.com/s3/PBM-Survey-Genpop-41)
Within Private browsing survey for en-us SHOULD BE ON (https://qsurvey.mozilla.com/s3/Private-Browsing-Survey)
