### ISSUE TITLE
roll out 10% US, 100 AUS mobile promotion

### ISSUE THREAD

**Issue by gregglind** [mozilla/self-repair-server#193]

**Comment by gregglind** [comment]
Rolling to 100% everywhere is way way easier

- We can do some 'western hemisphere' downsample.
- current rng is 'by day'.
-

**Comment by rayborn** [comment]
We're dropping the 100% AUS since the result while interesting doesn't presently appear actionable.

**Comment by evilpie** [comment]
This might have gone wrong again. https://www.reddit.com/r/firefox/comments/3v9zrw/so_how_many_times_do_i_need_to_close_this_before/ I would be interested to know who is responsible for approving this?
