### ISSUE TITLE
Potentially back breaking sampling issues

### ISSUE THREAD

**Issue by gregglind** [mozilla/self-repair-server#232]
*IF* we solve #212, then this affects sampling for heartbeat.

AFTER THIS,
- only users with localStorage enabled will ever see HB stuff.
  - this omits users with certain privacy sensitive settings.

ENABLES:
- use to comfortably know we aren't bothering people more than once.
- needful for experiments, messaging, and maybe Rebecca's 

IF WE DO THIS:
- I would increment to 0.13, and and a new version series (50) for HB and all other recipes.

**Comment by rjweiss** [comment]
I am not bothered by the "After this" caveat.  For the time being, it is acceptable to focus on those users with localStorage enabled.  Given future product direction, and given the implicit "do not bother me" signal that users are sending when they disable localStorage (meaning privacy-conscious), it is reasonable for us to primarily focus on understanding the responses of users who have localStorage enabled.

**Comment by gregglind** [comment]
fixed with #212
