### ISSUE TITLE
Launch Add-on Awareness Survey

### ISSUE THREAD

**Issue by MattGrimes** [mozilla/self-repair-server#266]
Launch Date: 04/19/2016
Survey URL: http://qsurvey.mozilla.com/s3/add-ons-awareness
Sample Size: 1000 per channel
Channel: Release, Beta
Locales: en*
Finish Date: 04/25/2016

**Comment by MattGrimes** [comment]
Actually let's do all channels. It'll be interesting to see how much more aware dev/nightly users are. Don't need 1000 from those channels, but a few hundred would be work.

**Comment by gregglind** [comment]
fixed by #269
