### ISSUE TITLE
check that search engines give useful stuff for 'please rate firefox' 

### ISSUE THREAD

**Issue by gregglind** [mozilla/self-repair-server#77]
and if not, create it.  (MDN, whatever)

**Comment by gregglind** [comment]
as of today, not much.  Maybe the 'learn more' thing will help there?

**Comment by gregglind** [comment]
Results here are mixed.

Yahoo:

Quoted:  "please rate firefox"  => right  (SUMO page)
unquoted:  please rate firefox => garbage

Google:
(both) => right  (SUMO page)

**Comment by willkg** [comment]
The top result for a Yahoo search of "please rate firefox" for me is:

```
Rate your Firefox experience (Heartbeat) | ...
support.mozilla.org/en-US/kb/rate-your-firefox...Cached

Rate your Firefox experience (Heartbeat) Mozilla is working hard to improve
Firefox and we need your help to make this happen. As you use Firefox, you
may be selected ... 
```

That seems right, no?

**Comment by willkg** [comment]
To clarify, I'm searching for unquoted "please rate firefox".

**Comment by gregglind** [comment]
Even better then!  I wonder why mine was bad!
