### ISSUE TITLE
Heartbeat trying to create two (person, survey, flow) items in the db.

### ISSUE THREAD

**Issue by gregglind** [mozilla/self-repair-server#84]
13:58 < willkg> gregglind: i'm getting a lot of errors from Input for heartbeat where it's trying to create two (person, survey, flow) items in the db.
13:59 < willkg> gregglind: i suspect it's a race... hb thingy sends one request and as that's processing, it sends another. and the code i've got on the server side has
                a sizeable enough gap between validation and transaction committing.
13:59 < willkg> plus person is NA so everyone has the same one.
13:59 < willkg> er, person is NA and everyone has the same survey id, too.
13:59 < willkg> so they only differ in flow id.
14:00 < willkg> gregglind: is it possible for two people to get the same flow id? where "possible" is defined as "likely enough that i'm getting 5 or so errors per day
                about it"?
14:00 < willkg> where "5" is actually more like "7".

**Comment by willkg** [comment]
I need to fix this bug before I can see what's going on: https://bugzilla.mozilla.org/show_bug.cgi?id=1136840

That bug is proving tricky.

**Comment by gregglind** [comment]
closed and fixed.  Results:  some data loss from early respondents, all fine now.
