### ISSUE TITLE
We should add a "More info" link for Heartbeat

### ISSUE THREAD

**Issue by MattGrimes** [mozilla/self-repair-server#87]
Got some feedback from a Mozillian that got the Heartbeat survey. They said they were at first concerned it wasn't from Mozilla. Of the feedback I received, I think adding a small "More info" or "What is this?" type link that takes you to the public wiki would be a good idea. Since Heartbeat is persistent across tabs they would see that it is indeed from Mozilla and still have the opportunity to give a score.

**Comment by willkg** [comment]
There was a post in yammer that was similar: person sees the bar, doesn't know what it is or where it came from and has no way to find out more details so suspects the worst. The yammer post was "liked", so maybe that suggests other people felt the same way.

**Comment by MattGrimes** [comment]
Do you happen to have that link? I looked and can't find it.

**Comment by gregglind** [comment]
(It is linked in the Bugzilla but for ux mods to heartbeat, will discus
with with peeps tomorrow)

**Comment by willkg** [comment]
I think this is the link:

https://www.yammer.com/mozillians/#/threads/show?threadId=505221702

**Comment by gregglind** [comment]
Active discussion at:  https://bugzilla.mozilla.org/show_bug.cgi?id=1137481#c16

**Comment by gregglind** [comment]
CLosed and completed.  Landed in firefox.
