### ISSUE TITLE
suggestions for question text

### ISSUE THREAD

**Issue by gregglind** [mozilla/self-repair-server#88]
per:  https://bugzilla.mozilla.org/show_bug.cgi?id=1137481#c19

Could we change from "Please rate Firefox" to "Give Mozilla your rating of Firefox" ? I think this would make it a lot more clear what the purpose is and also take advantage of how wide this notification bar is.

**Comment by nchelluri** [comment]
I personally was a bit confused when this message ("Please rate Firefox") came up and wondered if it was some kind of site javascript or browser malware. So I Googled the message and found this issue, and I agree with the suggested text change.

**Comment by gregglind** [comment]
At this time, won't be changing text, but new UI landed with "learn more" link.
